name: CI Bun App

on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.API_KEY }}
      TEST_ENV: ${{vars.TEST_ENV}}
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/reader-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get project name from package.json
        id: get_version
        run: |
          # Extrae el nombre del proyecto de package.json
          VERSION=$(jq -r .version package.json)
          echo "VERSION=VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          echo "Building Docker image with version ${{ steps.get_version.outputs.version }}"
          docker build \
            -t $DOCKER_IMAGE:latest \
            -t $DOCKER_IMAGE:${{ steps.get_version.outputs.version }} \
            .

      - name: Push Docker image
        run: |
          docker push $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:${{ steps.get_version.outputs.version }}