name: deploy.yml
on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.API_KEY }}
      TEST_ENV: ${{vars.TEST_ENV}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install and set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Start the application
        run: bun run start